spring:
  application:
    name: hr-payroll
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://hr-eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      workerService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 5s

feign:
  client:
    config:
      default:
        decode404: true