spring:
  application:
    name: hr-api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # Worker Service
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
            - Path=/hr-worker/**
          filters:
            - StripPrefix=1

        # Payroll Service
        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/hr-payroll/**
          filters:
            - StripPrefix=1

        # User Service
        - id: hr-user
          uri: lb://hr-user
          predicates:
            - Path=/hr-user/**
          filters:
            - StripPrefix=1

        # Oauth Service
        - id: hr-oauth
          uri: lb://hr-oauth
          predicates:
            - Path=/hr-oauth/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie
eureka:
  client:
    service-url:
      defaultZone: http://hr-eureka-server:8761/eureka

server:
  port: 8765

security: #mesma chave do oauth
  jwt:
    secret: MY-SECRET-KEY-MUST-BE-256-BITS-LONG!!
